[package]
name = "sandcastle-utils"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
reqwest.workspace = true
validator.workspace = true
mockall.workspace = true

[dev-dependencies]
