apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: sandcastle
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: sandcastle-dev-registry
    host: "0.0.0.0"
    hostPort: "5000"
files:
  - description: 'Install argo-cd'
    source: manifests/argo-cd-helmchart.yaml
    destination: k3s-manifests-custom/argo-cd.yaml
